import './index.scss';
import Providers from "@/store/Providers";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <Providers>
            <html lang="en">
            <body>{children}</body>
            </html>
        </Providers>
    )
}
